### ISSUE TITLE
似乎内存不足&有模块导入失败，原因未知

### ISSUE THREAD

**Issue by BlitherBoom812** [tljk/youdao_wordbook#2]
Traceback (most recent call last):
  File "boot.py", line 1, in <module>
  File "main.py", line 21, in <module>
MemoryError: memory allocation failed, allocating 1707 bytes
Traceback (most recent call last):
  File "main.py", line 21, in <module>
ImportError: can't import name EPD_2in13_V3
MicroPython v1.17 on 2021-09-22; ESP32 module with ESP32
Type "help()" for more information.

**Comment by tljk** [comment]
- 至少4m内存
- 尝试重启
- 使用mpy-cross编译除boot.py外的所以py文件，win请直接使用build.bat一键编译

**Comment by BlitherBoom812** [comment]
> * 至少4m内存
> * 尝试重启
> * 使用mpy-cross编译除boot.py外的所以py文件，win请直接使用build.bat一键编译

解决了，感谢！发现mpy-cross的版本必须是1.17，才能编译出mpy v5，和板子上的micropython版本适配，如果用最新版1.19编译出mpy v6就会不兼容。

**Comment by INPEIU** [comment]
我的问题与你一样，但是怎么更换mpy-cross的版本？
